name: Build & Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      # Uncomment and configure the step below when ready to use SSH deployment
      # - name: Deploy & Start Server via SSH
      #   uses: garygrossgarten/github-action-ssh@release
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       sudo apt update -y
      #       # sudo apt install -y nodejs npm
      #       # mkdir -p ~/hello-node
      #       # rm -rf ~/hello-node/*
      #       # cd ~/hello-node
      #       # git clone https://github.com/githuactions/mygithubactions.git .
      #       # npm install
      #       # pkill -f "node server.js" || true
      #       # nohup npm start > output.log 2>&1 &

      - name: Set up SSH agent with private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

          # Debugging: Check the content of the known_hosts file and SSH keys
          cat ~/.ssh/known_hosts
          cat ~/.ssh/id_rsa

          # Debugging: Try to SSH into the EC2 instance to see if it connects
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'echo "SSH connection successful!"'
